- hosts: localhost
  tasks:
    - gcp_compute_instance:
        auth_kind: serviceaccount
        can_ip_forward: no
        machine_type: "{{ DEFAULT_VM_SIZE }}"
        metadata: '{ "startup-script" : "{{ lookup('template', '{{ role_path }}/templates/userdata.txt.j2') }}", "description" : "{{ VM_DESCRIPTION }}" }'
        service_account_file: "{{ GCP_CREDENTIALS_FILE }}"
        name: "{{ VM_NAME }}"
        zone: "{{ DEFAULT_ZONE }}-a"
        state: present
        status: RUNNING
        network_interfaces:
          - access_configs:
              - name: ExternalNAT
                type: ONE_TO_ONE_NAT
        project: "{{ GCP_PROJECT_ID }}"
        disks:
          - index: 0
            boot: yes
            auto_delete: yes
            initialize_params:
              disk_size_gb: "{{ DEFAULT_DISK_SIZE }}"
              source_image: "{{ TEMPLATE_NAME }}"