- hosts: localhost
  connection: local
  tasks:
    - ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        region: "{{ AWS_REGION }}"
        id: "{{ VM_NAME }}"
        state: "{{ VM_STATE }}"