- hosts: localhost
  connection: local
  tasks:
    - vmware_guest:
        annotation: "{{ VM_DESCRIPTION }}"
        hostname: "{{ VCENTER_ADDRESS }}"
        username: "{{ VCENTER_USERNAME }}"
        password: "{{ VCENTER_PASSWORD }}"
        cluster: "{{ VCENTER_CLUSTER }}"
        datacenter: "{{ VCENTER_DATACENTER }}"
        datastore: "{{ VCENTER_DATASTORE }}"
        resource_pool: "{{ VCENTER_RESOURCE_POOL }}"
        name: "{{ VM_NAME }}"
        folder: "{{ VM_FOLDER }}"
        template: "{{ TEMPLATE_NAME }}"
        validate_certs: no
        state: poweredon
        networks:
        - name: "{{ NETWORK_NAME }}"
          device_type: "{{ NETWORK_DEVICE }}"
        customization:
          dns_servers: "{{ DOMAIN_DNS_SERVERS }}"
          domain: "{{ DOMAIN_DNS_NAME }}"
          hostname: "{{ VM_NAME }}"
      
    - vmware_guest_tools_wait:
        hostname: "{{ VCENTER_ADDRESS }}"
        username: "{{ VCENTER_USERNAME }}"
        password: "{{ VCENTER_PASSWORD }}"
        validate_certs: no
        name: "{{ VM_FOLDER }}"
        folder: "{{ VM_FOLDER }}"
      register: facts
    
    - add_host:
        name: "{{ facts.instance.ipv4 }}"
        groups: just_created
        ansible_user: "{{ DEFAULT_LOGIN }}"
        ansible_ssh_pass: "{{ DEFAULT_PASSWORD }}"
        ansible_become_user: "{{ DEFAULT_LOGIN }}"
        ansible_become_pass: "{{ DEFAULT_PASSWORD }}"
        
- hosts: just_created
  tasks:
    - authorized_key:
        user: "{{ DEFAULT_LOGIN }}"
        state: present
        key: "{{ SSH_KEY }}"
        
    - user:
        name: "{{ DEFAULT_LOGIN }}"
        shell: /bin/bash
        groups: sudo
        password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters') }}"