- hosts: localhost
  connection: local
  tasks:
    - vcenter_folder:
        hostname: "{{ VCENTER_ADDRESS }}"
        username: "{{ VCENTER_USERNAME }}"
        password: "{{ VCENTER_PASSWORD }}"
        datacenter: "{{ VCENTER_DATACENTER }}"
        folder_name: "{{ VM_FOLDER.split('/')[-1] }}"
        parent_folder: "{{ VM_FOLDER.split('/')[-2] }}"
        state: present
        validate_certs: no

    - vmware_guest:
        annotation: "{{ VM_DESCRIPTION }}"
        hostname: "{{ VCENTER_ADDRESS }}"
        username: "{{ VCENTER_USERNAME }}"
        password: "{{ VCENTER_PASSWORD }}"
        cluster: "{{ VCENTER_CLUSTER }}"
        datacenter: "{{ VCENTER_DATACENTER }}"
        datastore: "{{ VCENTER_DATASTORE }}"
        resource_pool: "{{ VCENTER_RESOURCE_POOL }}"
        name: "{{ VM_NAME }}"
        folder: "{{ VM_FOLDER }}"
        template: "{{ TEMPLATE_NAME }}"
        validate_certs: no
        state: poweredon
        networks:
        - name: "{{ NETWORK_NAME }}"
          device_type: "{{ NETWORK_DEVICE }}"
        customization:
          dns_servers: "{{ DOMAIN_DNS_SERVERS }}"
          domain: "{{ DOMAIN_DNS_NAME }}"
          hostname: "{{ VM_NAME }}"
          domainadmin: "{{ DOMAIN_ADMIN }}"
          domainadminpassword: "{{ DOMAIN_PASSWORD }}"
          joindomain: "{{ DOMAIN_NAME }}"
